channels:
  - defaults
dependencies:
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - ipykernel
  - python-utils
  - matplotlib
  - git
  - pdoc3
  - pydocstyle
  - pytest
  - pylint
  - selenium
  - autopep8
